### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/nodebb-plugin-attendance#13]
- [x] dont display "+0" when there are no "maybe" attendees
- [x] only display timestamp in details, not hint
- [x] reiterate timestamp to forum standard (2016-12-06 12:23), without seconds
- [x] dont display text on buttons in mobile (CSS Hack already live via Admin menu)
- [x] find solution to scroll/slide view to reveal all attendees
- [x] add prompt if you change status to "not attending" from "attending" via main button (because you lose your spot in the row)

**Comment by nomisum** [comment]
drag-scrolling geht scheinbar nur mit jquery oder zumindest JS :(
https://github.com/asvd/dragscroll

hiding scrollbar:
http://jsfiddle.net/2Kwsc/

**Comment by Fusselwurm** [comment]
> add prompt if you change status to "not attending" from "attending" via main button (because you lose your spot in the row)

hö… warum is das ein Problem?

**Comment by nomisum** [comment]
ist kein problem mehr, weil die reihenfolge in der liste grad per user ID ist und nicht mehr wie anfangs nach attendance zeitpunkt

**Comment by nomisum** [comment]
(was zu mehr Bewegung in der Liste führt und eher uncool is eigentlich)

**Comment by Fusselwurm** [comment]
@nomisum eh… ich hab das grad gestern gefixt. jetzt ist die Listenposition wieder nach Zeitpunkt. ^^

**Comment by nomisum** [comment]
jo, aber prompt ist vmtl trotzdem unnötig :)
