### ISSUE TITLE
slot out if user disattends

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/nodebb-plugin-attendance#25]
cant get it to work.

didnt know where to get current user uid to find his slot in slotting bind.

**Comment by Fusselwurm** [comment]
the fun thing is looping over all matches… huh. 
I guess I could add another endpoint to make it simpler and safer.

**Comment by Fusselwurm** [comment]
should be fixed (this plugin fires a hook that arma3-slotting latches onto)
