### ISSUE TITLE
slot plugin extension

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/nodebb-plugin-attendance#5]
- [x] enable saving of additional user input (e.g. slot numbers)
- [ ] find concept to display slot list without making too much of an effort for a) thread host, b) slotting persons and c) developer ;)

**Comment by Fusselwurm** [comment]
actually, I think that could be separate plugin.

**Comment by nomisum** [comment]
with dependency on this one?

choosing a slot without saying "i'm attending' shouldnt be possible for instance.
