### ISSUE TITLE
TypeError: $(...).attr(...) is undefined

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/nodebb-plugin-attendance#6]
`TypeError: $(...).attr(...) is undefined` beim Öffnen von Details, keine Fehler im UI

**Comment by Fusselwurm** [comment]
cant reproduce, might be fixed by my commit spree

**Comment by Fusselwurm** [comment]
problem persists in firefox

**Comment by nomisum** [comment]
i think this isnt plugin related
